name: "efficientnet_b3_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 32
instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 300, 300 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
