"""initia2

Revision ID: 9d2c51fe4907
Revises: 292e44a382ed
Create Date: 2023-11-07 06:51:13.449791

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9d2c51fe4907"
down_revision: Union[str, None] = "292e44a382ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_user", sa.Column("username", sa.String(), nullable=True))
    op.add_column("auth_user", sa.Column("image", sa.String(), nullable=True))
    op.drop_column("auth_user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_user",
        sa.Column("password", postgresql.BYTEA(), autoincrement=False, nullable=False),
    )
    op.drop_column("auth_user", "image")
    op.drop_column("auth_user", "username")
    # ### end Alembic commands ###
