name: "efficientnet_b3"
platform: "pytorch_libtorch"
max_batch_size : 32
dynamic_batching { }
instance_group [
  {
    count: 3
    kind: KIND_GPU
  }
]
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 300, 300 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1, 1000 ]
  }
]
