name: "efficientnet_b3"
platform: "pytorch_libtorch"
max_batch_size: 32
dynamic_batching { }
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 3, 320, 320 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]
